build:
  version: "1.0"

loans:
  message: "Welcome to MsBank loans related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@Msbank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721