spring:
  application:
    name: "configserver"
  profiles:
     active: native
#    active: git
  cloud:
    config:
      server:
        native:
#          search-locations: "classpath:/config/"
           search-locations: "file:///C://Users//User//Documents//config"

server:
  port: 8071