spring:
  application:
    name: "configserver"
  profiles:
#     active: native
      active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config/"
#           search-locations: "file:///C://Users//User//Documents//config"
            git:
              uri: "https://github.com/Shakir-Ali01/msbytes-config.git"
              default-label: main
              timeout: 5
              force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

encrypt:
  key: "6SD893HFHJK399JFJFHJF88"
server:
  port: 8071



management:
  endpoints:
    web:
      exposure:
        include: "*"