services:
  accounts:
    image: "boss215/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - msbank
  loans:
      image: "boss215/loans:s4"
      container_name: loans-ms
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
          - msbank

  cards:
      image: "boss215/cards:s4"
      container_name: cards-ms
      ports:
        - "9090:9090"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - msbank

networks:
    msbank:
      driver: "bridge"
