build:
  version: "3.0"

loans:
  message: "Welcome to MsBank loans related local APIs "
  contactDetails:
    name: "Amaal Greg - Developer"
    email: "amaal@msbank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934